openapi: 3.0.3
info:
  title: LLM Service Configuration API
  version: 1.0.0
  description: LLM 服务配置管理接口

servers:
  - url: http://localhost:8080
    description: Local development server

tags:
  - name: LLM Service
    description: LLM 服务配置管理

paths:
  /api/v1/llm-services:
    get:
      summary: 获取 LLM 服务列表
      operationId: listLlmServices
      tags: [LLM Service]
      parameters:
        - name: enabledOnly
          in: query
          schema:
            type: boolean
            default: false
          description: 是否只返回启用的服务
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmServiceListResponse'

    post:
      summary: 创建 LLM 服务
      operationId: createLlmService
      tags: [LLM Service]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLlmServiceRequest'
      responses:
        '201':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmServiceResponse'
        '400':
          description: 参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: 服务名称已存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/llm-services/{id}:
    get:
      summary: 获取 LLM 服务详情
      operationId: getLlmService
      tags: [LLM Service]
      parameters:
        - $ref: '#/components/parameters/LlmServiceId'
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmServiceResponse'
        '404':
          description: 服务不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      summary: 更新 LLM 服务
      operationId: updateLlmService
      tags: [LLM Service]
      parameters:
        - $ref: '#/components/parameters/LlmServiceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLlmServiceRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmServiceResponse'
        '404':
          description: 服务不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: 服务名称已存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: 删除 LLM 服务
      operationId: deleteLlmService
      tags: [LLM Service]
      parameters:
        - $ref: '#/components/parameters/LlmServiceId'
        - name: force
          in: query
          schema:
            type: boolean
            default: false
          description: 强制删除（忽略 Agent 引用警告）
      responses:
        '204':
          description: 删除成功
        '404':
          description: 服务不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: 服务被 Agent 引用，需要 force=true 强制删除
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/llm-services/{id}/status:
    put:
      summary: 更新服务状态（启用/禁用）
      operationId: updateLlmServiceStatus
      tags: [LLM Service]
      parameters:
        - $ref: '#/components/parameters/LlmServiceId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStatusRequest'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmServiceResponse'
        '400':
          description: 无法禁用唯一的默认服务
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 服务不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/llm-services/{id}/default:
    put:
      summary: 设置为默认服务
      operationId: setDefaultLlmService
      tags: [LLM Service]
      parameters:
        - $ref: '#/components/parameters/LlmServiceId'
      responses:
        '200':
          description: 设置成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LlmServiceResponse'
        '400':
          description: 只能将启用的服务设为默认
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 服务不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  parameters:
    LlmServiceId:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64
      description: LLM 服务 ID

  schemas:
    ProviderType:
      type: string
      enum: [OPENAI, CLAUDE, LOCAL, CUSTOM]
      description: |
        LLM 供应商类型:
        - OPENAI: OpenAI 服务
        - CLAUDE: Anthropic Claude 服务
        - LOCAL: 本地部署模型
        - CUSTOM: 自定义供应商

    ModelParameters:
      type: object
      description: 模型参数配置
      properties:
        modelName:
          type: string
          description: 模型名称
          example: gpt-4
        temperature:
          type: number
          format: double
          minimum: 0
          maximum: 2
          default: 1.0
          description: 温度参数，控制输出随机性
        maxTokens:
          type: integer
          minimum: 1
          maximum: 128000
          default: 4096
          description: 最大 Token 数
        topP:
          type: number
          format: double
          minimum: 0
          maximum: 1
          default: 1.0
          description: Top-P 参数（核采样）
        frequencyPenalty:
          type: number
          format: double
          minimum: -2
          maximum: 2
          default: 0
          description: 频率惩罚，降低重复内容
        presencePenalty:
          type: number
          format: double
          minimum: -2
          maximum: 2
          default: 0
          description: 存在惩罚，增加话题多样性
      required:
        - modelName

    CreateLlmServiceRequest:
      type: object
      description: 创建 LLM 服务请求
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: 服务名称（全局唯一）
          example: GPT-4 Production
        description:
          type: string
          maxLength: 500
          description: 服务描述
          example: 生产环境使用的 GPT-4 服务
        providerType:
          $ref: '#/components/schemas/ProviderType'
        endpoint:
          type: string
          format: uri
          description: API 端点地址
          example: https://api.openai.com/v1
        modelParameters:
          $ref: '#/components/schemas/ModelParameters'
        priority:
          type: integer
          minimum: 1
          maximum: 999
          default: 100
          description: 优先级（数字越小优先级越高）
        enabled:
          type: boolean
          default: true
          description: 是否启用
      required:
        - name
        - providerType
        - modelParameters

    UpdateLlmServiceRequest:
      type: object
      description: 更新 LLM 服务请求
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: 服务名称
        description:
          type: string
          maxLength: 500
          description: 服务描述
        providerType:
          $ref: '#/components/schemas/ProviderType'
        endpoint:
          type: string
          format: uri
          description: API 端点地址
        modelParameters:
          $ref: '#/components/schemas/ModelParameters'
        priority:
          type: integer
          minimum: 1
          maximum: 999
          description: 优先级

    UpdateStatusRequest:
      type: object
      description: 更新服务状态请求
      properties:
        enabled:
          type: boolean
          description: 是否启用
      required:
        - enabled

    LlmServiceResponse:
      type: object
      description: LLM 服务响应
      properties:
        id:
          type: integer
          format: int64
          description: 服务 ID
        name:
          type: string
          description: 服务名称
        description:
          type: string
          description: 服务描述
        providerType:
          $ref: '#/components/schemas/ProviderType'
        endpoint:
          type: string
          description: API 端点地址
        modelParameters:
          $ref: '#/components/schemas/ModelParameters'
        priority:
          type: integer
          description: 优先级
        enabled:
          type: boolean
          description: 是否启用
        isDefault:
          type: boolean
          description: 是否为默认服务
        createdAt:
          type: string
          format: date-time
          description: 创建时间
        updatedAt:
          type: string
          format: date-time
          description: 更新时间

    LlmServiceListResponse:
      type: object
      description: LLM 服务列表响应
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/LlmServiceResponse'
          description: 服务列表（按优先级排序）
        total:
          type: integer
          description: 总数

    ErrorResponse:
      type: object
      description: 错误响应
      properties:
        code:
          type: string
          description: 错误码
          example: LLM_SERVICE_NOT_FOUND
        message:
          type: string
          description: 错误信息
          example: LLM 服务不存在
        details:
          type: object
          description: 错误详情
          additionalProperties: true
